stages:
  - build
  - scan
  - push

variables:
  IMAGE_NAME: $HARBOR_HOST/library/$CI_PROJECT_NAME

build:
  image: docker:27.0.3
  stage: build
  services:
    - docker:27.0.3-dind
  before_script:
    - docker login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD $HARBOR_HOST
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_REF_SLUG -t $IMAGE_NAME:latest .

push:
  stage: push
  image: docker:27.0.3
  before_script:
    - docker login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD $HARBOR_HOST
  script:
    - docker push --all-tags $IMAGE_NAME
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
